version: "3.5"

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: server
    ports:
      - 8080:8080
    restart: always
    environment:
      - GITHUB_TOKEN
