version: "3.5"

services:
  server:
    build:
      context: https://${GITHUB_TOKEN}@github.com/braxtonhall/codeshovel-webservice.git
    container_name: backend
    ports:
      - 443:8080
    restart: always
    environment:
      - GITHUB_TOKEN
    volumes:
      - requests.csv:requests.csv
  frontend:
    build:
      context: https://${GITHUB_TOKEN}@github.com/braxtonhall/codeshovel-ui.git
    container_name: frontend
    ports:
    - 80:5000
    restart: always
